include ../extern/cppcore/
include ../extern/boostut/
include ../extern/pipes/

libs += ../extern/cppcore/lib{cppcore}
libs += ../extern/boostut/lib{boostut}
libs += ../extern/pipes/lib{pipes}

# ./ means "when building this dir, also build following target"
# executable hpm depends on utility library hpm, main.cxx.
# hpm.testscript is associated with the hpm executable
./: exe{hpm}: libue{hpm} {cxx}{main} testscript{hpm}

# Utility library used by hpm executable and
# the unit test executables
# Depends on hxx and cxx files in this directory
# except those who have .test.<something> in their name
# and those who are called main.
# Also depends on the libs
libue{hpm}: {hxx cxx}{** -**.test... -main} $libs

## All executables ending with .test are tests.
## So they are built and executed with `b test`.
## They are also not installed with `b install`.
exe{*.test}:
{
  test = true
  install = false
}


# All files ending with <somename>.test.cxx should be compiled
# to executables <somename>.test
# They depend on <somename>.test.hxx, <somename>.test.ixx, <somename>.test.txx
# If <somename>.test.testscript exist, it is associated with the test executable
# bin.whole = false makes so only the used functions are statically linked
# into the test executable
for t: cxx{**.test...}
{
  d = $directory($t)
  n = $name($t)...

  ./: $d/exe{$n}: $t $d/{hxx ixx txx}{+$n} $d/testscript{+$n}
  $d/exe{$n}: libue{hpm}: bin.whole = false
}

# Include our own header files
cxx.poptions =+ "-I$out_root" "-I$src_root"

# Include system wide opencv 4.4.0 headers
cxx.poptions =+ "-I/usr/local/include/opencv4"
cxx.libs =+ "-lopencv_core"
cxx.libs =+ "-lopencv_highgui"
cxx.libs =+ "-lopencv_imgcodecs"
cxx.libs =+ "-lopencv_imgproc"
cxx.libs =+ "-lopencv_calib3d"
cxx.libs =+ "-lopencv_features2d"
#
# Might need these in the future:
#-lopencv_stitching
#-lopencv_aruco
#-lopencv_bgsegm
#-lopencv_bioinspired
#-lopencv_ccalib
#-lopencv_dnn_objdetect
#-lopencv_dnn_superres
#-lopencv_dpm
#-lopencv_highgui
#-lopencv_face
#-lopencv_freetype
#-lopencv_fuzzy
#-lopencv_hfs
#-lopencv_img_hash
#-lopencv_intensity_transform
#-lopencv_line_descriptor
#-lopencv_quality
#-lopencv_rapid
#-lopencv_reg
#-lopencv_rgbd
#-lopencv_saliency
#-lopencv_stereo
#-lopencv_structured_light
#-lopencv_phase_unwrapping
#-lopencv_superres
#-lopencv_optflow
#-lopencv_surface_matching
#-lopencv_tracking
#-lopencv_datasets
#-lopencv_text
#-lopencv_dnn
#-lopencv_plot
#-lopencv_videostab
#-lopencv_videoio
#-lopencv_xfeatures2d
#-lopencv_shape
#-lopencv_ml
#-lopencv_ximgproc
#-lopencv_video
#-lopencv_xobjdetect
#-lopencv_objdetect
#-lopencv_imgcodecs
#-lopencv_flann
#-lopencv_xphoto
#-lopencv_photo
#-lopencv_core"
